### ISSUE TITLE
Roadmap still in progress?

### ISSUE THREAD

**Issue by jeremyworger** [Vincent-Maladiere/RingCode#1]
Hey there, is this project still being worked on for the decoding portion? Looks super cool.

**Comment by Vincent-Maladiere** [comment]
Hey @jeremydeanw, thanks! This project has been paused for the moment due to some lack of time on my end. You are more than welcome to contribute. I can assist you if you do.

**Comment by jeremyworger** [comment]
Hey thanks for the response. I'm actually wondering if the marker can be detected continuously through the barcode, as opposed to from the inside only, and not circular. I figure if for instance the center circle becomes smaller and smaller with more modules surrounding it, then a very small circle would be harder to detect, or that it would take up more physical space than the data encoded, and I was hoping to store more data.  
What I mean is, I was thinking overall a shape that is square or rectangular, and having the data "spiral" in square rings (like a tree trunk) outwards making up a bigger square/rectangle as you go along (some changeable aspect ratio). Then you could crop inwards at any point of the image and still obtain the data within the nearest square ring. 
Unfortunately im not really a coder, but I wonder if the groundwork you have here could lend to creating something like this. Just spitballin.

**Comment by jeremyworger** [comment]
Also considering all devices that capture the image will have aspect ratios that are not circular, but rectangular. I think you'd lose more data with a circular format opposed to a rectangle when cropping occurs, if markers could be continously detected. Basically like: https://www.dropbox.com/s/pjp10x5hikuuysh/data.png?dl=0  (red being if it was cropped, you'd lose the outside ring there)

**Comment by Vincent-Maladiere** [comment]
Thank you for these detailed insights!

>  I'm actually wondering if the marker can be detected continuously through the barcode, as opposed to from the inside only, and not circular.

1. Interesting, I think continuous detection could be possible with some extra work on encoding pattern recognition. This could be implemented with some geometric rules or even with machine learning on a lightweight model for fast detection.

>  I figure if for instance the center circle becomes smaller and smaller with more modules surrounding it, then a very small circle would be harder to detect, or that it would take up more physical space than the data encoded, and I was hoping to store more data.

2. Actually, the encoder enforces a minimum radius for the inner circle, so that detection can always be performed no matter the amount of data. Note that the maximum amount of data you can store on a Ring Code is rather small, as you can't store much on a QR Code either. 

> What I mean is, I was thinking overall a shape that is square or rectangular, and having the data "spiral" in square rings (like a tree trunk) outwards making up a bigger square/rectangle as you go along (some changeable aspect ratio). 

3. The encoder appends lines inwards, until reaching the maximum size. This design is convenient because it maintains a constant external radius but this is pretty arbitrary, so your idea seems feasible enough. You would just have to set a max radius and grow outwards from the min radius, as you suggested.

> Then you could crop inwards at any point of the image and still obtain the data within the nearest square ring.

4. I am not sure to understand this one, are you suggesting that every row of the "tree trunk" duplicates data? I do feel your core idea is not only to perform continuous detection but also continuous reading, correct?

> Unfortunately im not really a coder, but I wonder if the groundwork you have here could lend to creating something like this

5. Overall I think it could! :)

> Also considering all devices that capture the image will have aspect ratios that are not circular, but rectangular. I think you'd lose more data with a circular format opposed to a rectangle when cropping occurs, if markers could be continously detected

6. Yes, that's a very good point, and the main caveat of the circular Ring Code when every mobile device has a rectangular aspect ratio. Beyond its cool aesthetic, the circular design is almost spatially invariant (you could almost not tell whether it is upside down or not), which could yield some nice geometric properties. However, a rectangular shape is indeed more pragmatic and would probably provide better performance when it comes to detection.

**Comment by jeremyworger** [comment]
Sorry for 4, I got myself confused, I mean that the decoding be done after the capture of the image itself and not during. 
I'm not really a coder, so I think I mean detection of (squares or rectangles within the image) after capture, then reading. 
More or less if there would most likely be a cut off outside ring due to off-center cropping of the image, that particular ring would likely be damaged and unreadable...I would assume? 
I was thinking going ring per ring reading data within each ring, from the center outwards, till you reach an unreadable ring. 
Ive never seen a croppable lossy barcode, I think the inevitable loss of data would work well for certain types of linear data, like text, music or maybe even a gif. Not so much for storing image files, though what would be the point if you can just take a picture of a picture.  
I've got another idea for a sound-barcode format that is similar to this in a way, but is strictly sound based if you wanted to hear that one at somepoint too haha.

**Comment by Vincent-Maladiere** [comment]
Haha, I must admit that I'm intrigued by croppable lossy barcode :)

If your Bar Code is not damaged, you should always be able to read 100% of its data, given that you wait a bit longer to adjust and get an uncropped image of it. The risk is to deliver a partial reading of the data while you have all of it.

However, the Ring Code is very sensitive to area destruction (see page 26 of this [doc](https://www.dropbox.com/s/a62q4lotoyonnv7/P6_2015_Circular_Codes.pdf?dl=0)), so bringing loss resilience could be of great use. A lot of extra development will be needed for this feature.

That being said, I'm pretty curious about your sound-barcode format. Could you give more details about it?

**Comment by jeremyworger** [comment]
- Sent you an email.
